.TH TITLE 1 "February 2024" "1.1" "Manpage for title"

.SH NAME
title \- Terminal Title Setter

.SH SYNOPSIS
.B title
[\fIOPTIONS\fR] '\fITITLE\fR'

.SH DESCRIPTION
This program allows you to set the title of your terminal window. It accepts command-line arguments to set or unset the title.

.SH OPTIONS
.TP
.BR \-h, \-\-help
Show help message.

.TP
.BR \-v, \-\-version
Display program version.

.SH EXAMPLES
To set the terminal title, run:

.B title '\fIMy title'\fR

To unset the terminal title, run:

.B title

.SH AUTHORS
PhateValleyman
.br
https://github.com/PhateValleyman
.br
Jonas.Ned@outlook.com
